# Generated by Django 5.1 on 2024-09-14 19:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion_categoria', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id_cliente', models.AutoField(primary_key=True, serialize=False)),
                ('rut_cliente', models.CharField(max_length=15)),
                ('nombre_cliente', models.CharField(max_length=100)),
                ('email_cliente', models.EmailField(max_length=254)),
                ('fono_cliente', models.CharField(max_length=20)),
                ('direccion_cliente', models.TextField()),
                ('fecha_registro_cl', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Docto_Venta',
            fields=[
                ('nro_docto', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Tipo_Docto_Venta',
            fields=[
                ('id_tipo_docto', models.AutoField(primary_key=True, serialize=False)),
                ('descrip_tipo_docto', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('SKU_PROD', models.CharField(max_length=50, primary_key=True, serialize=False, unique=True)),
                ('NOMBRE_PROD', models.CharField(max_length=100)),
                ('DESCRIPCION', models.TextField()),
                ('PRECIO_PROD', models.DecimalField(decimal_places=2, max_digits=10)),
                ('IMAGEN', models.ImageField(blank=True, null=True, upload_to='media/')),
                ('STOCK_PROD', models.PositiveIntegerField()),
                ('CATEGORIA', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.categoria')),
            ],
        ),
        migrations.CreateModel(
            name='Detalle_Venta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField()),
                ('precio_unit', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_neto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('id_docto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.docto_venta')),
                ('sku_producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.producto')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grupos', models.ManyToManyField(to='auth.group')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='docto_venta',
            name='tipo_docto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tipo_docto_venta'),
        ),
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id_venta', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_venta', models.DateTimeField()),
                ('total_venta', models.DecimalField(decimal_places=2, max_digits=10)),
                ('id_cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.cliente')),
            ],
        ),
        migrations.AddField(
            model_name='docto_venta',
            name='id_venta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.venta'),
        ),
    ]
